- actions/sonar/1.0/dice.yml
- actions/sonar/1.0/internal/analysis.go
- actions/sonar/1.0/internal/command.go
- actions/sonar/1.0/internal/package_manager.go
- actions/sonar/1.0/internal/result_meta.go
- actions/sonar/1.0/internal/sonar_ce_task.go
- actions/sonar/1.0/internal/sonar_quality_gate.go
> Sonar Action: add quality gate conditions details

- actions/agent/1.0/dice.yml
> actionagent upgrade md5

- actions/git-checkout/1.0/dice.yml
- actions/git-checkout/1.0/internal/assets/common.sh
- actions/java-build/1.0/Dockerfile
- actions/java-build/1.0/dice.yml
git checkout action add branch info, java-buuld action use specified version
> git checkout action add branch info, java-buuld action use specified version

- actions/assert/1.0/internal/pkg/build/execute.go
- actions/assert/1.0/internal/pkg/conf/conf.go
value use number will return error: `panic: failed to parse json ENV: ACTION_ASSERTS, value: [{"actualValue":"1","assert":"=","value":1}], err: json: cannot unmarshal number into Go struct field Assert.value of type string`, so change value type use interface
> value user interface and doAssert value use JsonOneLine parse value

- actions/reportengine/1.0/dice.yml
- actions/reportengine/1.0/spec.yml
fix reportengine when erda isn't in default namespace
> reportengine support namespaced erda

- actions/add-nodes/1.0/dice.yml
/kind bug
add multi node bugfix, using ',' as separator
Specified Reviewers:
/assign @luobily
> add multi node bugfix

- actions/release/1.0/internal/pkg/execute.go
- actions/release/1.0/spec.yml
test link: [test](https://erda.dev.terminus.io/terminus/dop/projects/2/apps/124/repo)
this application was originally a normal application, I executed the pipeline to be deployed, and then I manually modified the application mode to a project_service application, and then the deployment reported an error
> release action check application mode, project_service mode cannot ploy

- actions/testplan-run/1.0/internal/conf/conf.go
- actions/testplan-run/1.0/internal/testplan-run/testplan-run.go
- actions/testplan-run/1.0/spec.yml
add Asynchronous ability for testplan-run action
In order not to waste too much time in unimportant automated tests when executing ci/cd, asynchronous capabilities are provided
> add Asynchronous ability for testplan-run action

- actions/mysql-cli/1.0/internal/pkg/build/execute.go
Returning error early will cause the error message of the mysql command to not be returned
erda-issue: [erda-issue](https://terminus-org.erda.cloud/erda/dop/projects/387/issues/bug?id=207989&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)
> mysql-cli remove return command run error

- actions/buildpack/1.0/internal/run/pack/pack.go
- actions/buildpack/1.0/internal/run/util/hashdir/hashdir.go
> Fixed the issue that buildpack action does not output build-result
issue:[issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/bug?id=203677&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=0&type=BUG)
[测试链接](https://erda.dev.terminus.io/terminus/dop/projects/1/apps/3/pipeline?nodeId=MS8zL3RyZWUvbWFzdGVyL3BpcGVsaW5lLnltbA%3D%3D&pipelineID=26)
测试结果
)
> Fixed the issue that buildpack action does not output build-result

- actions/testplan-run/1.0/internal/conf/conf.go
- actions/testplan-run/1.0/internal/testplan-run/testplan-run.go
- actions/testplan-run/1.0/spec.yml
Added a field to continue execution after failure in testplan-action
[Test link](https://erda.dev.terminus.io/terminus/dop/projects/1/apps/3/pipeline?nodeId=MS8zL3RyZWUvZGV2ZWxvcC9waXBlbGluZS55bWw%3D&pipelineID=205)
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=216864&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG)
> Added a field to continue execution after failure in testplan-action

- Makefile
- actions/java-dependency-check/1.0/Dockerfile
- actions/java-dependency-check/1.0/internal/pkg/build/execute.go
- actions/java-dependency-check/1.0/internal/pkg/conf/conf.go
- actions/java-dependency-check/1.0/spec.yml
fix java-dependency-check:
- update NVD using maven plugin's update-only phrase
- add some useful action params, such as debug mode, maven plugin version, auto update NVD, etc
- fix upload limitation to /api/files. `.html` is forbidden, so use one tar for all reports.
Tested in HKCI and Roche and works fine.
> java-dependency-check: update NVD; add custom configs

- actions/release/1.0/Dockerfile
- actions/release/1.0/dice.yml
- actions/release/1.0/internal/cmd/main.go
- actions/release/1.0/internal/conf/conf.go
- actions/release/1.0/internal/pkg/execute.go
- actions/release/1.0/spec.yml
The graphical interface will lose release_mobile. The reason for the loss of the release_mobile field should be that the graphical editing interface is used, which does not have this field on the graphical interface.
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=226639&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
> android release bugfix

- actions/git-checkout/1.0/Dockerfile
- actions/git-checkout/1.0/dice.yml
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/
```text
Unfortunately this does not apply to OpenSSL 1.0.2 which always prefers the untrusted chain and if that chain contains a path that leads to an expired trusted root certificate (DST Root CA X3), it will be selected for the certificate verification and the expiration will be reported.
```
> Upgrade git checkout openssl

- actions/git-checkout/1.0/Dockerfile
- actions/git-checkout/1.0/dice.yml
[Related Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=243046&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=467&type=TASK)
> fix: git-checkout action downgrade base alpine version from 3.14 to 3.12 to fix dns issue

- actions/git-checkout/1.0/Dockerfile
- actions/git-checkout/1.0/dice.yml
[previous pr](https://github.com/erda-project/erda-actions/pull/248) missing second alpine version replace in Dockerfile.
> fix: git-checkout action downgrade alpine version for dns issue

- actions/java/1.0/Dockerfile
use registry.erda.cloud for openjfx8
> java-action: Dockerfile openjfx8 use registry.erda.cloud

- actions/ios/1.0/dice.yml
- actions/ios/1.0/internal/pkg/build/build.go
- pkg/dice/file_upload.go
The ios task timed out when uploading files, the reason is that there are .git files in the compressed files
> ios upload file timeout time set

- dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.18/Dockerfile
- dockerfiles/terminus-nodejs/node.14.18.2/Dockerfile.debian.npm.6.14
chore: use retaged images for node related dockerfile
> chore: use retaged images for node releated dockerfile

- actions/mysql-assert/1.0/dice.yml
- actions/mysql-assert/1.0/internal/pkg/build/execute.go
- actions/mysql-cli/1.0/dice.yml
- actions/mysql-cli/1.0/internal/pkg/build/execute.go
The mysql password has special characters, causing the connection to mysql to fail
> fix: The mysql password has special characters, causing the connection to mysql to fail

- actions/erda-mysql-migration/1.0-56/dice.yml
- actions/erda-mysql-migration/1.0-57/dice.yml
- actions/erda-mysql-migration/1.0-80/dice.yml
feat: udpate erda-mysql-migration images: use character set utf8 in sandbox
> feat: udpate erda-mysql-migration images: use character set utf8 in sandbox

- actions/agent/1.0/dice.yml
fix action agent blocked due to stdout log
> fix: action agent blocked due to stdout log

- actions/loop/1.0/dice.yml
expand resource of loop action, because 32 mem may cause oomkilled
> fix: expand resource of loop action
