erda-project/erda-actions

actions/mysql-cli/1.0/Dockerfile, actions/mysql-cli/1.0/dice.yml, actions/mysql-cli/1.0/internal/pkg/build/execute.go
mysql-cli action support json result
=> mysql-cli action support json result

Makefile, actions/dice-version-archive/1.0/Dockerfile, actions/dice-version-archive/1.0/README.MD, actions/dice-version-archive/1.0/dice.yml, actions/dice-version-archive/1.0/internal/archive/diceyaml.go, actions/dice-version-archive/1.0/internal/archive/gittar.go, actions/dice-version-archive/1.0/internal/archive/migration.go, actions/dice-version-archive/1.0/internal/archive/version.go, actions/dice-version-archive/1.0/internal/cmd/main.go, actions/dice-version-archive/1.0/internal/config/config.go, actions/dice-version-archive/1.0/spec.yml
=> feature: add dice-version-archive

actions/dice-version-archive/1.0/dice.yml, actions/dice-version-archive/1.0/internal/archive/access_api.go, actions/dice-version-archive/1.0/internal/archive/diceyaml.go, actions/dice-version-archive/1.0/internal/archive/gittar.go, actions/dice-version-archive/1.0/internal/archive/request.go, actions/dice-version-archive/1.0/internal/cmd/main.go, actions/dice-version-archive/1.0/internal/config/config.go, actions/dice-version-archive/1.0/spec.yml, pkg/metawriter/metawriter.go
=> feature: read dice.yml from dicehub

actions/dice-version-archive/1.0/dice.yml, actions/dice-version-archive/1.0/internal/cmd/main.go
fix archived dice.yml path error
=> fix: fix archived dice.yml path error

actions/dice-version-archive/1.0/README.MD, actions/dice-version-archive/1.0/dice.yml, actions/dice-version-archive/1.0/internal/archive/diceyaml.go, actions/dice-version-archive/1.0/internal/config/config.go, go.mod
- update dice.yml image
- set http request header "Accept": "application/x-yaml" while getting dice.yml from dicehub
- update denpendencies (otherwise there will be a bug when processing dice.yml.)
@sfwn  🙏 💕 💕 💕
=> feature: update denpendencies; set dicehub reqeust header

actions/buildpack/1.0/bp/java/build/maven/Dockerfile, actions/buildpack/1.0/dice.yml
see related issue: https://github.com/moby/moby/issues/37965
=> workaround for multi stage layer copy error

actions/dice-version-archive/1.0/spec.yml, actions/dice/1.0/spec.yml, actions/dockerfile/1.0/spec.yml, actions/golang/1.0/spec.yml, actions/java-build/1.0/spec.yml, actions/java/1.0/spec.yml, actions/js-build/1.0/spec.yml, actions/js/1.0/spec.yml, actions/php/1.0/spec.yml, actions/release/1.0/spec.yml
=> Remove http header in logoUrl

actions/buildpack/1.0/dice.yml, actions/java/1.0/dice.yml
=> Update java and buildpack action

actions/mysql-cli/1.0/dice.yml, actions/mysql-cli/1.0/internal/pkg/build/execute.go, actions/redis-cli/1.0/dice.yml, actions/redis-cli/1.0/internal/pkg/build/execute.go
bug fix mysql-cli and redis-cli run error
=> bug fix mysql-cli and redis-cli run error

actions/git-checkout/1.0/dice.yml, actions/git-checkout/1.0/internal/assets/internal_run.sh
git-checkout use commit checkout code
=> git-checkout use commit checkout code

actions/cs-kubernetes-scale/1.0/dice.yml
chang cs scale image same to ack default image
@luobily
=> update cs kubernetes scale image

actions/mysql-cli/1.0/spec.yml
mysql-cli add search result outputs
=> mysql-cli add search result outputs

.dice/pipelines/update-java-agent.yml
see: [erda pipeline](https://erda-org.erda.cloud/erda/workBench/projects/387/apps/6300/pipeline?nodeId=Mzg3LzYzMDAvdHJlZS9mZWF0dXJlL2FkZC1waXBlbGluZS1mb3ItamF2YS1hZ2VudC8uZGljZS9waXBlbGluZXMvdXBkYXRlLWphdmEtYWdlbnQueW1s&pipelineID=10882274)
=> feature: add pipeline to update java-agent

Makefile, actions/push-extensions/1.0/Dockerfile, actions/push-extensions/1.0/README.md, actions/push-extensions/1.0/dice.yml, actions/push-extensions/1.0/internal/cli/main.go, actions/push-extensions/1.0/internal/client/client.go, actions/push-extensions/1.0/internal/client/status.go, actions/push-extensions/1.0/internal/cmd/main.go, actions/push-extensions/1.0/internal/config/config.go, actions/push-extensions/1.0/internal/workdir/repo.go, actions/push-extensions/1.0/internal/workdir/type.go, actions/push-extensions/1.0/internal/workdir/version.go, actions/push-extensions/1.0/spec.yml
the action `push-extensions` is used to push actions and addons in repos to the erda platform
=> feature: add action push-extensions

actions/java-build/1.0/Dockerfile, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java-build/1.0/dice.yml, actions/java-build/1.0/internal/pkg/build/execute.go
=> java-build add action agent

actions/js/1.0/README.md
add Node.js verson description for js action readme
=> add Node.js version description for js action readme

Makefile, actions/sonar/1.0/dice.yml, actions/sonar/1.0/internal/analysis.go, actions/sonar/1.0/internal/command.go, actions/sonar/1.0/internal/package_manager.go, actions/sonar/1.0/internal/result_meta.go, actions/sonar/1.0/internal/sonar_ce_task.go, actions/sonar/1.0/internal/sonar_quality_gate.go, actions/sonar/1.0/sonarqube/8.4.2/Dockerfile
=> upgrade sonarqube mybatis version to fix security issue

actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack/1.0/dice.yml, actions/gitbook/1.0/dice.yml, actions/java-build/1.0/dice.yml, actions/java/1.0/dice.yml, actions/js-build/1.0/dice.yml, actions/js/1.0/dice.yml, actions/php/1.0/dice.yml
=> update actions version

actions/archive-extensions/1.0/dice.yml, actions/archive-release/1.0/dice.yml
feature: replace docker registry with registry.erdsa.coud
=> feature: replace docker registry with registry.erdsa.coud

actions/js-build/1.0/Dockerfile
=> feature: add git to js-build action

actions/js-build/1.0/dice.yml
feature: update js-build image which is built on erda pipeline
=> feature: update js-build image which is built on erda pipeline

actions/erda-mysql-migration/1.0/dice.yml
update erda-mysql-migration image
=> feature: update erda-mysql-migration image

Makefile, actions/app-create/1.0/Dockerfile, actions/app-create/1.0/README.md, actions/app-create/1.0/dice.yml, actions/app-create/1.0/internal/appCreate/appCreate.go, actions/app-create/1.0/internal/appCreate/run.go, actions/app-create/1.0/internal/cmd/main.go, actions/app-create/1.0/internal/conf/conf.go, actions/app-create/1.0/spec.yml, actions/app-run/1.0/Dockerfile, actions/app-run/1.0/README.md, actions/app-run/1.0/dice.yml, actions/app-run/1.0/internal/appRun/appRun.go, actions/app-run/1.0/internal/appRun/appRun_test.go, actions/app-run/1.0/internal/appRun/run.go, actions/app-run/1.0/internal/cmd/main.go, actions/app-run/1.0/internal/conf/conf.go, actions/app-run/1.0/spec.yml
add app create action，app run action
=> add app create action，app run action

actions/archive-release/1.0/dice.yml, actions/erda-mysql-migration/1.0/dice.yml
update archive-release and erda-mysql-migration image
=> feature: update archive-release and erda-mysql-migration image

actions/archive-release/1.0/internal/config/config.go, actions/archive-release/1.0/spec.yml
to support custom oss directory, that we can set it "archived-versions" for enterprise package and "archive-versions-community" for community package.
=> feature: to support custom oss directory

actions/assert/1.0/internal/pkg/build/execute.go, actions/jsonparse/1.0/internal/pkg/build/execute.go
assert and jsonparse action use stdOutput
=> assert and jsonparse action use stdOutput

actions/archive-extensions/1.0/internal/config/config.go, actions/archive-extensions/1.0/spec.yml
to support custom oss directory for archive-extensions
=> feature: to support custom oss directory for archive-extensions

actions/archive-extensions/1.0/dice.yml, actions/archive-release/1.0/dice.yml
feature: update archive-extensions and archive-release images
=> feature: update archive-extensions and archive-release images

actions/api-test/2.0/spec.yml
api-test spec add executor field
=> api-test spec add executor field

actions/app-create/1.0/dice.yml, actions/app-run/1.0/dice.yml, actions/assert/1.0/dice.yml, actions/jsonparse/1.0/dice.yml
=> update some action image

actions/push-extensions/1.0/internal/client/client.go
feature: fix the log of requesting dicehub
=> feature: fix the log of requesting dicehub

actions/git-checkout/1.0/internal/assets/internal_run.sh
Related PR: https://github.com/erda-project/erda/pull/1071#issue-692223458
=> git-checkout rerun get before code, cron task get new code

actions/erda-mysql-migration-lint/1.0/dice.yml, actions/erda-mysql-migration-lint/1.0/internal/cmd/main.go, actions/erda-mysql-migration-lint/1.0/internal/config/config.go, actions/erda-mysql-migration/1.0/dice.yml, go.sum
update images for erda-mysql-migration and erda-mysql-migration-lint, they are built on Erda pipeline
=> feature: update images for erda-mysql-migration and erda-mysql-migration-lint

actions/cluster-resource/1.0/dice.yml, actions/cs-kubernetes/1.0/dice.yml
/kind bugfix cluster create action image
/assign @luobily
=> cluster create action image update

Makefile, actions/testplan-run/1.0/Dockerfile, actions/testplan-run/1.0/README.md, actions/testplan-run/1.0/dice.yml, actions/testplan-run/1.0/internal/cmd/main.go, actions/testplan-run/1.0/internal/conf/conf.go, actions/testplan-run/1.0/internal/testplan-run/run.go, actions/testplan-run/1.0/internal/testplan-run/testplan-run.go, actions/testplan-run/1.0/spec.yml
Execute the corresponding test plan according to the test plan name and parameter configuration, and then wait for the execution to complete
issue:
https://terminus-org.app.terminus.io/erda/workBench/projects/387/issues/requirement?id=70716&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=requirement
=> add testplan-run action

actions/archive-release/1.0/internal/cmd/main.go, actions/archive-release/1.0/internal/config/config.go, actions/archive-release/1.0/internal/oss/oss.go, actions/erda-mysql-migration-lint/1.0/internal/cmd/main.go, actions/erda-mysql-migration-lint/1.0/internal/config/config.go, actions/erda-mysql-migration-lint/1.0/spec.yml, actions/erda-mysql-migration/1.0/internal/action/cmd/main.go, actions/erda-mysql-migration/1.0/internal/action/migration/config.go, actions/erda-mysql-migration/1.0/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0/spec.yml, go.mod, go.sum
delete git ref path from OSS before uploading
refact it and make code clean
add parameter control flow. it allows user to skip migration lint, sandbox, pre-migration, real migration (dry run)
=> feature: delete git ref path from OSS before uploading

actions/testplan-run/1.0/dice.yml, actions/testplan-run/1.0/internal/testplan-run/testplan-run.go, actions/testscene-run/1.0/dice.yml, actions/testscene-run/1.0/internal/testscene-run/testscene-run.go
The action will fail When the use testplan and testscene execution fails
=> add fail status

actions/erda-mysql-migration/1.0/Dockerfile, actions/erda-mysql-migration/1.0/my.cnf
fix mysql client charater error
=> feature: fix mysql client character error

actions/app-run/1.0/Dockerfile, actions/app-run/1.0/dice.yml, actions/app-run/1.0/internal/appCancel/cancel/cancel.go, actions/app-run/1.0/internal/appCancel/cmd/main.go, actions/app-run/1.0/internal/appRun/appRun.go, actions/app-run/1.0/internal/conf/conf.go, actions/app-run/1.0/spec.yml
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=72603&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
link pr: https://github.com/erda-project/erda/pull/1294#issue-702936273
=> pipeline cancel should cancel app-run action pipelineID

actions/erda-mysql-migration/1.0/internal/local/cmd/main.go, actions/erda-mysql-migration/1.0/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0/spec.yml, go.mod, go.sum
- update erda migrator dependencies
- allow to use external sandbox
=> feature: update erda migrator dependencies

actions/agent/1.0/dice.yml
agent action report std err if matched custom regexp
=> agent report std error if match regexp

actions/erda-mysql-migration/1.0/internal/local/config/configuration.go
- fix sandbox envs from
- fix typo
=> fix envs from

actions/erda-mysql-migration-lint/1.0/dice.yml, actions/erda-mysql-migration/1.0/dice.yml, actions/erda-mysql-migration/1.0/internal/local/config/configuration.go
update erda-mysql-migration image
=> update erda-mysql-migration image

actions/dice/1.0/internal/dice/client.go, actions/dice/1.0/internal/dice/conf.go, actions/dice/1.0/internal/dice/deploy.go, actions/dice/1.0/internal/post/cmd/main.go, actions/dice/1.0/internal/run/cmd/main.go, pkg/log/log.go
**What type of this PR**
/kind polish
**What this PR does / why we need it:**
fix: polish the print of dice action
**Which issue(s) this PR fixes:**
https://erda.cloud/erda/dop/projects/387/issues/bug?id=204242&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzFdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTI2MSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG
reviewer: @sfwn
=> fix: polish the print of dice action

actions/buildpack-aliyun/1.0/bp/java/pack/edas-dubbo-cnooc/start.sh, actions/buildpack-aliyun/1.0/bp/java/pack/edas-dubbo/start.sh, actions/buildpack-aliyun/1.0/bp/java/pack/edas/start.sh, actions/buildpack-aliyun/1.0/bp/java/pack/springboot-asia/entrypoint.sh, actions/buildpack-aliyun/1.0/bp/java/pack/springboot/entrypoint.sh, actions/buildpack-aliyun/1.0/sync_assets.sh, actions/buildpack/1.0/bp/java/pack/edas-dubbo-cnooc/start.sh, actions/buildpack/1.0/bp/java/pack/edas-dubbo/start.sh, actions/buildpack/1.0/bp/java/pack/edas/start.sh, actions/buildpack/1.0/bp/java/pack/springboot-asia/entrypoint.sh, actions/buildpack/1.0/bp/java/pack/springboot/entrypoint.sh, actions/java/1.0/comp/openjdk/entrypoint.sh, actions/java/1.0/comp/tomcat/entrypoint.sh
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=203458&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)
=> java and buildpack action add  JAVA_OPTS_ENABLED env to clear erda JAVA_OPTS

actions/api-test/2.0/spec.yml, actions/app-create/1.0/spec.yml, actions/app-run/1.0/spec.yml, actions/assert/1.0/spec.yml, actions/custom-script/1.0/spec.yml, actions/docker-push/1.0/spec.yml, actions/dockerfile/1.0/spec.yml, actions/git-checkout/1.0/spec.yml, actions/java-build/1.0/spec.yml, actions/js-build/1.0/spec.yml, actions/jsonparse/1.0/spec.yml, actions/mysql-cli/1.0/spec.yml, actions/redis-cli/1.0/spec.yml, actions/testplan-run/1.0/spec.yml, actions/testscene-run/1.0/spec.yml, actions/unit-test/1.0/spec.yml
add project_service lable for some action
Used to filter the aciton in the pipeline in project-level applications
=> add project_service lable for some action

Makefile, actions/erda-pkg-release-enterprise/1.0/Dockerfile, actions/erda-pkg-release-enterprise/1.0/README.MD, actions/erda-pkg-release-enterprise/1.0/dice.yml, actions/erda-pkg-release-enterprise/1.0/internal/bin/build, actions/erda-pkg-release-enterprise/1.0/internal/bin/build.go, actions/erda-pkg-release-enterprise/1.0/internal/cmd/main.go, actions/erda-pkg-release-enterprise/1.0/internal/config/config.go, actions/erda-pkg-release-enterprise/1.0/internal/pkg/env.go, actions/erda-pkg-release-enterprise/1.0/internal/pkg/execute.go, actions/erda-pkg-release-enterprise/1.0/internal/pkg/repo.go, actions/erda-pkg-release-enterprise/1.0/pkg/env.go, actions/erda-pkg-release-enterprise/1.0/pkg/metafile.go, actions/erda-pkg-release-enterprise/1.0/pkg/oss.go, actions/erda-pkg-release-enterprise/1.0/pkg/repo.go, actions/erda-pkg-release-enterprise/1.0/pkg/utils.go, actions/erda-pkg-release-enterprise/1.0/spec.yml, actions/erda-pkg-release-public/1.0/Dockerfile, actions/erda-pkg-release-public/1.0/README.MD, actions/erda-pkg-release-public/1.0/dice.yml, actions/erda-pkg-release-public/1.0/internal/bin/build_package.go, actions/erda-pkg-release-public/1.0/internal/bin/build_package.sh, actions/erda-pkg-release-public/1.0/internal/bin/compose.go, actions/erda-pkg-release-public/1.0/internal/bin/compose.sh, actions/erda-pkg-release-public/1.0/internal/cmd/main.go, actions/erda-pkg-release-public/1.0/internal/config/config.go, actions/erda-pkg-release-public/1.0/internal/pkg/env.go, actions/erda-pkg-release-public/1.0/internal/pkg/execute.go, actions/erda-pkg-release-public/1.0/internal/pkg/repo.go, actions/erda-pkg-release-public/1.0/spec.yml
add erda install package release cation
=> add erda install package release cation

actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack/1.0/dice.yml, actions/java/1.0/dice.yml, actions/release/1.0/dice.yml
1. buildpack buildpack-aliyun java action add DISABLE_PRESET_JAVA_OPTS env config to clear erda JAVA_OPTS
2. release action add application mode check, project level application can not use release action
=> change buildpack java release image

actions/erda-mysql-migration-lint/1.0/dice.yml, actions/erda-mysql-migration/1.0/dice.yml, actions/erda-mysql-migration/1.0/internal/local/config/configuration.go, actions/erda-pkg-release-enterprise/1.0/dice.yml, actions/erda-pkg-release-enterprise/1.0/internal/bin/build, go.mod, go.sum
=> update 3 actions images

actions/erda-mysql-migration/1.0/internal/local/config/configuration.go, actions/erda-pkg-release-enterprise/1.0/dice.yml, actions/erda-pkg-release-enterprise/1.0/internal/bin/build.go
update erda-pkg-release-enterprise-action image
=> update erda-pkg-release-enterprise-action image

actions/reportengine/1.0/dice.yml
- https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204938&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG
=> bugfix for json tag

actions/manual-review/1.0/internal/conf/conf.go, actions/manual-review/1.0/internal/manualReview/manualReview.go, actions/manual-review/1.0/spec.yml
add Default value of waiting time，Prevent polling time from being too short
=> add Default value of waiting time

actions/dice/1.0/dice.yml
=> fix: update dice image

actions/mysql-cli/1.0/dice.yml
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=207989&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)
https://github.com/erda-project/erda-actions/pull/151#issue-713939295
=> mysql-cli remove return command run error

Makefile, actions/golang/1.0/Dockerfile, dockerfiles/terminus-golang/Dockerfile, dockerfiles/terminus-golang/build.sh
=> upgrade go version

actions/golang/1.0/dice.yml
=> upgrade golang action image

actions/buildpack/1.0/sync_assets.sh, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java/1.0/comp/download_spot_agent.sh
=> add 1.3 version java agent

actions/buildpack/1.0/dice.yml, actions/java-build/1.0/dice.yml, actions/java/1.0/dice.yml
upgrade java buildpack build image
=> upgrade java buildpack build image

actions/testplan-run/1.0/dice.yml
=> update testplan-run mirror

dockerfiles/terminus-herd/herd.1.1.8-alpine-node.14.17/Dockerfile, dockerfiles/terminus-herd/herd.1.1.8-debian-node.14.17/Dockerfile, dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.alpine.npm.6.14
1. 修复了Alpine 镜像兼容性问题；
2. Debian-herd 镜像加了 ping 命令；
=> update alpine and debian images

actions/testplan-run/1.0/dice.yml
=> change testplan-run image

actions/gitbook/1.0/internal/pkg/build/execute.go, actions/gitbook/1.0/internal/pkg/conf/conf.go, actions/java-build/1.0/internal/pkg/build/execute.go
add docker login for some actions
[erda link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=210081&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDgwNSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=TASK)
[test link](https://erda.dev.terminus.io/terminus/dop/projects/1/apps/3/pipeline?nodeId=MS8zL3RyZWUvZGV2ZWxvcC8uZGljZS9waXBlbGluZXMvYnVpbGRwYWNrLnltbA%3D%3D&pipelineID=11504)
=> add docker login for some actions

actions/buildpack-aliyun/1.0/internal/run/build/build.go, actions/buildpack-aliyun/1.0/internal/run/pack/pack.go, actions/buildpack/1.0/internal/run/build/build.go, actions/buildpack/1.0/internal/run/pack/pack.go, actions/docker-push/1.0/internal/main.go, actions/dockerfile/1.0/internal/pkg/build/execute.go, actions/gitbook/1.0/internal/pkg/build/execute.go, actions/golang/1.0/internal/pkg/build/build.go, actions/java/1.0/internal/pkg/build/execute.go, actions/js/1.0/internal/pkg/build/execute.go, actions/php/1.0/internal/pkg/build/build.go, actions/release/1.0/internal/pkg/migration.go, pkg/docker/docker.go
Add new error message for docker push
[erda link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=201539&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDA4MDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=REQUIREMENT)
buildpack action test
dockerfile aciton test
=> Add new error message for docker push

dockerfiles/terminus-herd/herd.1.1.10-debian-node.14.17/Dockerfile, dockerfiles/terminus-herd/herd.1.1.10-debian-node.14.17/deploy.sh
=> feature: Add herd 1.1.10 image related docker file

actions/erda-pkg-release-public/1.0/dice.yml
rename registry from cn-hangzhou to erda.cloud
@luobily
=> feature: rename registry from cn-hangzhou to erda.cloud

dockerfiles/terminus-nodejs/node.12.22/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.12.22/deploy.sh
添加新镜像 terminus-debian-node:12.22-lts 相关 Dockerfile等
=> feature: add node 12.22.6 docker file for debian os

actions/jsonparse/1.0/README.md
update jsonparse docs，Add more detailed documentation
=> update jsonparse docs

actions/mysql-cli/1.0/spec.yml
If the 1.2 version of erda uses mysql-cli, there will be compatibility issues
=> rollback mysql-cli spec

pkg/docker/docker.go
fix does not return an error when docker push
=> fix does not return an error when docker push

Makefile, actions/mysql-assert/1.0/Dockerfile, actions/mysql-assert/1.0/README.md, actions/mysql-assert/1.0/dice.yml, actions/mysql-assert/1.0/internal/cmd/main.go, actions/mysql-assert/1.0/internal/pkg/build/execute.go, actions/mysql-assert/1.0/internal/pkg/conf/conf.go, actions/mysql-assert/1.0/spec.yml
mysql-cli jsonparse assert a combination of three actions
=> mysql cli with jsonparse and assert

actions/app-create/1.0/dice.yml, actions/app-create/1.0/internal/appCreate/appCreate.go
git username password should url code, it incloud @ and :
erda-issue: [erda-issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222952&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
=> app-create decode git username git password

actions/release/1.0/dice.yml
=> release-action: update image

actions/release/1.0/internal/conf/conf.go, actions/release/1.0/internal/pkg/execute.go
=> release-action: aabinfo support number

actions/agent/1.0/dice.yml
Tested in test-new and hkci.
Related Erda pr: #1898
=> action-agent: upgrade image, related erda pr: #1898

actions/echo/1.0/dice.yml, actions/echo/1.3/Dockerfile, actions/echo/1.3/README.md, actions/echo/1.3/dice.yml, actions/echo/1.3/internal/.keep, actions/echo/1.3/spec.yml
/feature 
add echo 1.3 with support loop 
/assignee
@luobily
=> add echo 1.3 with loop

actions/archive-release/1.0/Dockerfile, actions/archive-release/1.0/dice.yml, actions/archive-release/1.0/internal/cmd/main.go, actions/archive-release/1.0/internal/oss/oss.go, actions/archive-release/1.0/internal/oss/oss_test.go, actions/archive-release/1.0/internal/oss/progress.go, actions/archive-release/1.0/internal/repo/releasedyml.go, actions/archive-release/1.0/internal/repo/releasedyml_test.go, actions/archive-release/1.0/internal/repo/repo.go, pkg/metawriter/metawriter.go
delete oss object recursively
07ee586
=> delete oss object recursively

actions/add-nodes/1.0/dice.yml, actions/upgrade-edge-cluster/1.0/dice.yml
=> update action mem

actions/erda-mysql-migration/1.0-56/Dockerfile, actions/erda-mysql-migration/1.0-56/dice.yml, dockerfiles/erda-migration/sandbox56/Dockerfile, dockerfiles/erda-migration/sandbox56/my.cnf
set `innodb_large_prefix = on` for sandbox on msql 5.6
=> set `innodb_large_prefix = on` for sandbox on msql 5.6

actions/erda-mysql-migration/1.0-56/dice.yml, actions/erda-mysql-migration/1.0-57/dice.yml, actions/erda-mysql-migration/1.0-80/dice.yml, go.mod, go.sum
update erda-mysql-migration images: remove dll-reversing
=> update erda-mysql-migration images: remove dll-reversing

actions/js-build/1.0/README.md, actions/js/1.0/README.md
update nodejs use docs, add dest_dir annotation
erda-issue: [erda-issue](https://erda.cloud/erda/dop/projects/387/ticket?id=219130&pageNo=2&title=%E7%AD%94%E7%96%91)
- [] I made sure to check the compatibility of the erda version statemented in the action's spec.yml.
=> update nodejs use docs, add dest_dir annotation

actions/wait/1.0/README.md, actions/wait/1.0/dice.yml, actions/wait/1.0/spec.yml
=> wait action executor

actions/buildpack-aliyun/1.0/sync_assets.sh, actions/buildpack/1.0/sync_assets.sh, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java/1.0/comp/download_spot_agent.sh
=> update java-agent 1.4 version

actions/testplan-run/1.0/spec.yml
change name of action testplan-run
=> change name of action testplan-run

.github/workflows/image-check.yml, actions/reportengine/1.0/dice.yml, actions/virtual-offline-image/1.0/dice.yml
add extension image format check, check result e.g.:
check failed:
check success:
Based on the results, the following mirror image was corrected.
Please view it: @luobily @sfwn
=> feature: add erda-action extension image format check

actions/mobile-template/1.0/Dockerfile, actions/mobile-template/1.0/dice.yml
There is a problem with the original template tool version, and an error will appear in the generated code. You need to upgrade the next version
=> update mobile template version

actions/php/1.0/dice.yml
=> rebuild php action image

actions/erda-mysql-migration/1.0-56/Dockerfile, actions/erda-mysql-migration/1.0-56/dice.yml, actions/erda-mysql-migration/1.0-57/Dockerfile, actions/erda-mysql-migration/1.0-57/dice.yml, actions/erda-mysql-migration/1.0-57/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0-80/Dockerfile, actions/erda-mysql-migration/1.0-80/dice.yml, dockerfiles/erda-migration/sandbox56/Dockerfile, dockerfiles/erda-migration/sandbox57/Dockerfile, dockerfiles/erda-migration/sandbox80/Dockerfile, pkg/envconf/load.go, pkg/envconf/load_test.go
not trim charset utf8,utf8mb4 while parsing create table stmt
=> not trim charset utf8,utf8mb4 while parsing create table stmt

actions/buildpack-aliyun/1.0/sync_assets.sh, actions/buildpack/1.0/sync_assets.sh, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java/1.0/comp/download_spot_agent.sh
=> Download java agent 1.5

actions/golang/1.0/dice.yml
upgrade golang action docker cli
[erda issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249463&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG)
=> upgrade golang action docker cli

Makefile, actions/contrast-security/1.0/Dockerfile, actions/contrast-security/1.0/README.md, actions/contrast-security/1.0/cmd/main.go, actions/contrast-security/1.0/dice.yml, actions/contrast-security/1.0/internal/pkg/build/execute.go, actions/contrast-security/1.0/internal/pkg/conf/conf.go, actions/contrast-security/1.0/spec.yml
add contrast security action
[erda issue](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=252009&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=TASK)
=> add contrast security action

actions/agent/1.0/dice.yml
related PR: https://github.com/erda-project/erda/pull/3121
=> action-agent: fix callback speed issue

actions/contrast-security/1.0/spec.yml, actions/email/1.0/dice.yml
update contract secuirty public and category
=> update contract secuirty public and category

actions/contrast-security/1.0/dice.yml, actions/contrast-security/1.0/internal/pkg/build/execute.go
add limit when request contrast security
=> contrast security add limit

actions/add-nodes/1.0/dice.yml
/feature add-node action: update tool url
/assignee @luobily
=> add-node action: update tool url

actions/email/1.0/Dockerfile, actions/email/1.0/dice.yml, actions/email/1.0/internal/pkg/build/execute.go, actions/email/1.0/internal/pkg/files/sendmail.py
Sending GSSAPI auth mail using Python
=> send gassapi auth email

actions/buildpack-aliyun/1.0/Dockerfile, actions/buildpack-aliyun/1.0/internal/run/build/buildkit.go, actions/buildpack-aliyun/1.0/internal/run/conf/params.go, actions/buildpack-aliyun/1.0/internal/run/execute.go, actions/buildpack-aliyun/1.0/internal/run/pack/pack_buildkit.go, actions/buildpack/1.0/Dockerfile, actions/buildpack/1.0/internal/run/build/buildkit.go, actions/buildpack/1.0/internal/run/conf/params.go, actions/buildpack/1.0/internal/run/execute.go, actions/buildpack/1.0/internal/run/pack/pack_buildkit.go, actions/gitbook/1.0/Dockerfile, actions/gitbook/1.0/internal/pkg/build/execute.go, actions/gitbook/1.0/internal/pkg/conf/conf.go, actions/golang/1.0/Dockerfile, actions/golang/1.0/internal/conf/conf.go, actions/golang/1.0/internal/pkg/build/build.go, actions/js/1.0/Dockerfile, actions/js/1.0/internal/pkg/build/execute.go, actions/js/1.0/internal/pkg/conf/conf.go, actions/release/1.0/Dockerfile, actions/release/1.0/internal/conf/conf.go, actions/release/1.0/internal/pkg/docker.go, actions/release/1.0/internal/pkg/migration.go
=> build action support buildkit

go.mod, go.sum, pkg/docker/docker.go
write auth info to ~/.docker/config.json if without docker.sock
@luobily @sixther-dc
=> feature: add auth for buildkit

actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack/1.0/dice.yml, actions/custom-script/1.0/dice.yml, actions/docker-push/1.0/dice.yml, actions/dockerfile/1.0/dice.yml, actions/gitbook/1.0/dice.yml, actions/golang/1.0/dice.yml, actions/java/1.0/dice.yml, actions/js/1.0/dice.yml, actions/php/1.0/dice.yml, actions/release/1.0/dice.yml
=> action release for buildkit

actions/java/1.0/dice.yml, actions/java/1.0/internal/pkg/build/pack.go
java action container version not support
=> java container type bugfix

actions/buildpack-aliyun/1.0/internal/run/build/buildkit.go, actions/buildpack/1.0/internal/run/build/buildkit.go, actions/dockerfile/1.0/internal/pkg/build/execute.go, actions/gitbook/1.0/internal/pkg/build/execute.go, actions/golang/1.0/internal/pkg/build/build.go, actions/java/1.0/internal/pkg/build/pack.go, actions/js/1.0/internal/pkg/build/execute.go, actions/php/1.0/internal/pkg/build/build.go, actions/release/1.0/internal/pkg/docker.go, actions/release/1.0/internal/pkg/migration.go
remove registry insecure skip
@luobily @sixther-dc
=> fix: remove registry insecure skip

actions/golang/1.0/dice.yml
feature: golang without registry insecure skip
@sixther-dc
=> feature: golang without registry insecure skip

actions/agent/1.0/dice.yml
[Related Erda Issue](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwXSwibWVtYmVyIjpbIjkyIiwiMTAwMDU2MCJdfQ%3D%3D&id=268081&iterationID=772&pId=0&type=TASK)
=> update agent image

actions/custom-script/2.0/Dockerfile, actions/custom-script/2.0/README.md, actions/custom-script/2.0/assets/settings.xml, actions/custom-script/2.0/dice.yml, actions/custom-script/2.0/spec.yml
[erda link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MV0sIm1lbWJlciI6WyIxMDAxMjA1Il19&id=229488&iterationID=772&pId=0&type=REQUIREMENT)
=> add custom script 2.0 version

actions/buildpack-aliyun/1.0/bp/node/pack/spa/Dockerfile, actions/buildpack/1.0/bp/node/pack/spa/Dockerfile
=> fix: buildpack spa error at pack stage.

actions/unit-test/1.0/spec.yml
=> unit test locale

actions/agent/1.0/dice.yml
[issue-link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzIsNjgwLDg4MSw4ODNdLCJtZW1iZXIiOlsiMTAwMTIwNSJdfQ%3D%3D&id=270099&iterationID=772&pId=0&type=BUG)
=> upgrade action agent

actions/extract-repo-version/1.0/dice.yml, actions/extract-repo-version/1.0/run.sh
=> add time dimension to version

actions/extract-repo-version/1.0/dice.yml, actions/extract-repo-version/1.0/run.sh
Special treatment for release/master
=> Special treatment for release/master

dockerfiles/terminus-nodejs/node.12.13/Dockerfile.node.12.13, dockerfiles/terminus-nodejs/node.12.13/deploy.sh
upgrade node12.13 git version to 2.24
=> upgrade node12.13 git version to 2.24

dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.18/Dockerfile, dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.18/deploy.sh, dockerfiles/terminus-nodejs/node.14.18.2/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.14.18.2/deploy.sh
Add new Dockerfiles for node 14.18-LTS with pnpm installed
=> feat: add new dockerfiles for node 14.18-LTS with pnpm installed

actions/dice/2.0/Dockerfile, actions/dice/2.0/README.md, actions/dice/2.0/dice.yml, actions/dice/2.0/internal/dice/apistructs.go, actions/dice/2.0/internal/dice/cancel.go, actions/dice/2.0/internal/dice/cancel_test.go, actions/dice/2.0/internal/dice/client.go, actions/dice/2.0/internal/dice/conf.go, actions/dice/2.0/internal/dice/deploy.go, actions/dice/2.0/internal/dice/deploy_test.go, actions/dice/2.0/internal/post/cmd/main.go, actions/dice/2.0/internal/run/cmd/main.go, actions/dice/2.0/internal/utils/filehelper.go, actions/dice/2.0/spec.yml
=> feat: dice action for deployment order

Makefile, actions/dingtalk-robot-msg/1.0/Dockerfile, actions/dingtalk-robot-msg/1.0/dice.yml, actions/dingtalk-robot-msg/1.0/run.sh, actions/dingtalk-robot-msg/1.0/spec.yml
=> feat: add dingtalk-robot-msg action

actions/dice-deploy-redeploy/1.0/dice.yml, actions/dice-deploy-redeploy/1.0/internal/dice-deploy-redeploy/dice-deploy-redeploy.go, actions/dice-deploy-redeploy/1.0/spec.yml
surpport redeploy a runtime based application name.  this is only used for a runtime which deployed base a released, not a whole pipeline deploy.
=> feat: surpport redeploy a runtime based application name

actions/email/1.0/dice.yml, actions/email/1.0/internal/pkg/build/execute.go
Send emails with custom subject and sender
=> Send emails with custom subject and sender

actions/erda-get-service-addr/1.0/Dockerfile, actions/erda-get-service-addr/1.0/README.md, actions/erda-get-service-addr/1.0/dice.yml, actions/erda-get-service-addr/1.0/internal/erda-get-service-addr/runtime-services.go, actions/erda-get-service-addr/1.0/internal/post/cmd/main.go, actions/erda-get-service-addr/1.0/internal/run/cmd/main.go, actions/erda-get-service-addr/1.0/spec.yml
add action runtime-services for get runtime's services' address
=> feat: add action runtime-services for get runtime's services' addr

Makefile, actions/erda-get-addon-info/1.0/Dockerfile, actions/erda-get-addon-info/1.0/README.md, actions/erda-get-addon-info/1.0/dice.yml, actions/erda-get-addon-info/1.0/internal/erda-get-addon-info/erda-get-addon-info.go, actions/erda-get-addon-info/1.0/internal/post/cmd/main.go, actions/erda-get-addon-info/1.0/internal/run/cmd/main.go, actions/erda-get-addon-info/1.0/spec.yml
add erda-get-addon-info action to get addon configs for an runtime's  specific addon name
=> feat: add erda-get-addon-info action to get addon configs 

actions/erda-add-app-config/1.0/Dockerfile, actions/erda-add-app-config/1.0/dice.yml, actions/erda-add-app-config/1.0/internal/erda-add-app-config/erda-add-app-config.go, actions/erda-add-app-config/1.0/internal/run/cmd/main.go, actions/erda-add-app-config/1.0/spec.yml
add erda-add-app-config action
=> add erda-add-app-config action

actions/reportengine/1.0/dice.yml
reportengine support international
=> fix: reportengine support international

actions/erda-add-app-config/1.0/spec.yml, actions/erda-get-service-addr/1.0/spec.yml
=> opts: add international

actions/redis-cli/1.0/spec.yml
Remove some extra characters from redis config
=> Remove some extra characters from redis config

actions/dice/2.0/dice.yml
=> feat: upgrade dice action

actions/erda-get-addon-info/1.0/README.md, actions/erda-get-addon-info/1.0/internal/erda-get-addon-info/erda-get-addon-info.go, actions/erda-get-addon-info/1.0/spec.yml
Action erda-get-addon-info support use application name
=> feat:erda-get-addon-info support use application name

actions/android/1.0/Dockerfile, actions/js-build/1.0/Dockerfile, dockerfiles/terminus-herd/herd.1.1.10-debian-node.12.22/Dockerfile, dockerfiles/terminus-herd/herd.1.1.11-alpine-node.14.17/Dockerfile, dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.17/Dockerfile, dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.18/Dockerfile, dockerfiles/terminus-nodejs/node.12.13/Dockerfile.node.12.13, dockerfiles/terminus-nodejs/node.12.22/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.12.8.1/Dockerfile.node.12.8.1.npm.6.10.2, dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.alpine.npm.6.14, dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.14.18.2/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.9.11.1/Dockerfile.node.9.11.1.npm.5.6.0
See REF: https://developer.aliyun.com/article/801032
=> chore: change npm mirror domain from npm.taobao.org to npmmirror.com

dockerfiles/terminus-tomcat/tomcat.v7.0.96-jdk8/Dockerfile, dockerfiles/terminus-tomcat/tomcat.v8.5.43-jdk8/Dockerfile
change download url for dockerfile of tomcat
[erda issue link](https://erda.cloud/erda/dop/projects/387/issues/all?id=282294&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=TASK)
=> fix: change download url for dockerfile of tomcat

actions/mysql-assert/1.0/spec.yml
=> fix: Fix i18n key typo

actions/android/1.0/spec.yml, actions/ios/1.0/spec.yml
update category of spec.yml to ios and android
=> fix: update category of spec.yml to ios and android

actions/sonar/1.0/README.md, actions/sonar/1.0/sonarqube/8.9.6/Dockerfile, actions/sonar/1.0/sonarqube/8.9.6/entrypoint.sh
add 8.9.6-version sonarQube dockerfile
=> add 8.9.6-version sonarQube dockerfile

actions/assert/1.0/README.md
The assertvalue in the document is incorrect and should be changed to actualvalue
=> assert docs update

Makefile, actions/release-fetch/1.0/Dockerfile, actions/release-fetch/1.0/dice.yml, actions/release-fetch/1.0/main.go
add release_name output for release-fetch action
=> feat: add release_name output for release-fetch action

actions/extract-repo-version/1.0/dice.yml, actions/extract-repo-version/1.0/run.sh
change full version style like:
version=1.6-master+20220224141309
major_minor_version=1.6-master
image_tag=1.6-master-20220224141309-a19e5bc75
=> refactor: change full version style like

go.mod
feat: use character set utf8 in sandbox
=> feat: use character set utf8 in sandbox

actions/dice/2.0/dice.yml
=> fix: rollback dice action 2.0

actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/config/config.go, actions/project-artifacts/1.0/internal/oapi/oapi.go
feat: remove update project release
=> feat: remove update project release

actions/dice/2.0/Dockerfile, actions/dice/2.0/internal/conf/conf.go, actions/dice/2.0/internal/pkg/dice/deploy/do.go
deprecated workspace params
@sixther-dc
=> fix: deprecated workspace params

actions/buildpack/1.0/Dockerfile, actions/buildpack/1.0/dice.yml, actions/buildpack/1.0/sync_assets.sh, actions/java-build/1.0/Dockerfile, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java-build/1.0/dice.yml
- buildpack action
- java-build action
=> Update java agent

actions/android/1.0/spec.yml, actions/custom-script/1.0/spec.yml, actions/custom-script/2.0/spec.yml
add eci_disable label for custom-action and andriod action
=> add eci_disable label for custom-action and andriod action

actions/archive-extensions/1.0/internal/config/config.go, actions/archive-release/1.0/internal/config/config.go, actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/cmd/main.go, actions/project-artifacts/1.0/internal/config/config.go, actions/project-artifacts/1.0/internal/oapi/oapi.go, actions/project-artifacts/1.0/internal/oapi/releases.go
feat: list all applications releases by a big pageSize
=> feat: list all applications releases by a big pageSize

actions/extract-repo-version/1.0/dice.yml, actions/extract-repo-version/1.0/run.sh
=> refactor: change version rule

actions/buildpack-aliyun/1.0/bp/node/pack/herd/Dockerfile, actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack-aliyun/1.0/internal/run/build/build.go, actions/buildpack-aliyun/1.0/internal/run/build/buildkit.go, actions/buildpack-aliyun/1.0/internal/run/pack/pack.go, actions/buildpack-aliyun/1.0/internal/run/pack/pack_buildkit.go, actions/buildpack-aliyun/1.0/sync_assets.sh, actions/buildpack/1.0/bp/node/pack/herd/Dockerfile, actions/buildpack/1.0/dice.yml, actions/buildpack/1.0/internal/run/build/build.go, actions/buildpack/1.0/internal/run/build/buildkit.go, actions/buildpack/1.0/internal/run/pack/pack.go, actions/buildpack/1.0/internal/run/pack/pack_buildkit.go, actions/buildpack/1.0/sync_assets.sh, actions/java-build/1.0/comp/download_spot_agent.sh, actions/java-build/1.0/dice.yml, actions/java-build/1.0/internal/pkg/build/execute.go, actions/java/1.0/comp/download_spot_agent.sh, actions/java/1.0/comp/openjdk/Dockerfile, actions/java/1.0/comp/tomcat/Dockerfile, actions/java/1.0/dice.yml, actions/java/1.0/internal/pkg/build/pack.go, pkg/version/version_util.go
java and nodejs inject the latest monitor agent for those actions:
- java
- java-build
- buildpack
- buildpack-aliyun
=> feat: latest agent

actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/config/config.go, actions/project-artifacts/1.0/spec.yml
=> feat: support location

Makefile, actions/buildpack/1.0/spec.yml, actions/project-package/1.0/Dockerfile, actions/project-package/1.0/dice.yml, actions/project-package/1.0/internal/cmd/main.go, actions/project-package/1.0/internal/config/config.go, actions/project-package/1.0/internal/pkg/execute.go, actions/project-package/1.0/spec.yml
project-package action to make package of project by pipeline
/approve @luobily @dspo
=> action for project package

actions/release/1.0/Dockerfile, actions/release/1.0/dice.yml
=> fix: use bsdtar to fix release action tar error on eci

actions/erda-mysql-migration/1.0-56/Dockerfile, actions/erda-mysql-migration/1.0-57/Dockerfile, actions/erda-mysql-migration/1.0-57/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0-80/Dockerfile
=> feat: sampling

actions/project-artifacts/1.0/README.md, actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/cmd/main.go, actions/project-artifacts/1.0/internal/config/config.go, actions/project-artifacts/1.0/internal/oapi/oapi.go, actions/project-artifacts/1.0/internal/oapi/types.go, actions/project-artifacts/1.0/spec.yml
Support project release with deploy modes
=> feat: release deploy modes

actions/erda-mysql-migration/1.0-56/dice.yml, actions/erda-mysql-migration/1.0-57/dice.yml, actions/erda-mysql-migration/1.0-57/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0-80/dice.yml
=> refactor(migrate): change to use cert file content

actions/js-build/1.0/internal/pkg/build/execute.go
=> fix(js-build): fix js-build execute syntax

actions/erda-mysql-migration/1.0-56/Dockerfile, actions/erda-mysql-migration/1.0-56/dice.yml, actions/erda-mysql-migration/1.0-57/Dockerfile, actions/erda-mysql-migration/1.0-57/dice.yml, actions/erda-mysql-migration/1.0-57/internal/common/common.go, actions/erda-mysql-migration/1.0-57/internal/local/config/configuration.go, actions/erda-mysql-migration/1.0-80/Dockerfile, actions/erda-mysql-migration/1.0-80/dice.yml, actions/release-fetch/1.0/spec.yml
=> feat: migration in runtime

actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/cmd/main.go
fix: set expose=true in default mode
=> fix: set expose=true in default mode

actions/dice/2.0/dice.yml, actions/dice/2.0/internal/pkg/dice/deploy/do.go
fix: deployment order deploy duplicate        @sixther-dc
=> fix: deployment order deploy duplicate

actions/agent/1.0/dice.yml
[erda-issue](https://erda.cloud/erda/dop/projects/387/issues/all?id=300237&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAxMjA1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&tab=TASK&type=TASK)
=> feat: action-agent support edge pipeline

actions/app-run/1.0/internal/appRun/appRun.go, actions/app-run/1.0/internal/appRun/appRun_test.go
app run support .erda/pipelines pipeline yml
=> app run support .erda/pipelines pipeline yml

actions/android/1.0/internal/pkg/build/build.go
=> fix: Temporarily solve the problem that the pipelineID exceeds the mximum versionCode

actions/android/1.0/Dockerfile, actions/android/1.0/dice.yml
=> feat:  update image and  add `GOPROXY` env to android dockerfile

actions/agent/1.0/dice.yml
action agent support set file stream timeout
[related pr](https://github.com/erda-project/erda/pull/4803)
=> fix: action agent support set file stream timeout

actions/golang/1.0/dice.yml
=> fix: golang version upgrade to 1.16.7

actions/erda-mysql-migration/1.0-56/Dockerfile, actions/erda-mysql-migration/1.0-56/dice.yml, actions/erda-mysql-migration/1.0-57/Dockerfile, actions/erda-mysql-migration/1.0-57/dice.yml, actions/erda-mysql-migration/1.0-80/Dockerfile, actions/erda-mysql-migration/1.0-80/dice.yml, dockerfiles/erda-migration/sandbox56/Dockerfile, dockerfiles/erda-migration/sandbox57/Dockerfile, dockerfiles/erda-migration/sandbox80/Dockerfile, go.mod, go.sum
- use alicloud pipy source
- update erda dependencies
=> feat: udpate erda-mysql-migration

actions/app-run/1.0/Dockerfile, actions/app-run/1.0/dice.yml, actions/app-run/1.0/internal/appRun/appRun.go, actions/app-run/1.0/internal/conf/conf.go, actions/app-run/1.0/spec.yml
app-run support failed by pipeline status
=> app-run support failed by pipeline status

actions/loop/1.0/spec.yml
loop action add default strategy
=> fix: loop action add default strategy

actions/release/1.0/dice.yml, actions/release/1.0/internal/diceyml/define.go, actions/release/1.0/internal/diceyml/define_test.go, go.mod, go.sum
fix: valid image name after generate release
=> fix: valid image name after generate release

actions/release/1.0/dice.yml
=> fix: update release image

dockerfiles/terminus-herd/herd.1.1.15-debian-node.14.18/Dockerfile, dockerfiles/terminus-herd/herd.1.1.15-debian-node.14.18/deploy.sh
add herd@1.1.15 node@14.18.2 dockerfile
=> Feature/herd 1.1.15 dockerfile

actions/email/1.0/spec.yml, actions/python-script/3.21/spec.yml, actions/sonar/1.0/spec.yml
=> fix: import action content

Makefile, actions/dice/2.0/dice.yml, actions/dice/2.0/internal/pkg/dice/callback/callback.go, actions/dice/2.0/internal/pkg/dice/deploy/do.go, actions/dice/2.0/spec.yml, pkg/metawriter/metawriter.go
feat: dice action 2.0 metawriter
=> feat: dice action 2.0 metawriter

actions/project-artifacts/1.0/Dockerfile, actions/project-artifacts/1.0/dice.yml, actions/project-artifacts/1.0/internal/cmd/main.go, actions/project-artifacts/1.0/internal/config/config.go
feat: read change log from file
=> feat: read change log from file

actions/wait/1.0/spec.yml
=> fix: add category for wait action

actions/java-lint/1.0/spec.yml, actions/java-unit/1.0/spec.yml, actions/testplan/1.0/spec.yml
=> fix: update category of some action

actions/app-run/1.0/dice.yml, actions/app-run/1.0/internal/appCancel/cancel/cancel.go, actions/app-run/1.0/internal/appRun/appRun.go
fix app-run http error
[related erda issue](https://erda.cloud/erda/dop/projects/387/issues/iteration/1250/all?id=317305&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyI5MiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1250&type=TASK)
=> fix app-run http error

actions/app-run/1.0/dice.yml
=> fix: update app-run action image

actions/agent/1.0/dice.yml
This reverts commit 62d0588cfa126f9b3ddb6f39e905322fd4c9fb9c.
=> Revert "fix action agent blocked due to stdout log (#436)"

actions/buildpack-aliyun/1.0/Dockerfile, actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack-aliyun/1.0/internal/run/build/buildkit.go, actions/buildpack-aliyun/1.0/internal/run/conf/params.go, actions/buildpack-aliyun/1.0/internal/run/pack/pack_buildkit.go, actions/buildpack/1.0/Dockerfile, actions/buildpack/1.0/dice.yml, actions/buildpack/1.0/internal/run/build/buildkit.go, actions/buildpack/1.0/internal/run/conf/params.go, actions/buildpack/1.0/internal/run/pack/pack_buildkit.go, actions/gitbook/1.0/Dockerfile, actions/gitbook/1.0/dice.yml, actions/gitbook/1.0/internal/pkg/build/execute.go, actions/gitbook/1.0/internal/pkg/conf/conf.go, actions/golang/1.0/Dockerfile, actions/golang/1.0/dice.yml, actions/golang/1.0/internal/conf/conf.go, actions/golang/1.0/internal/pkg/build/build.go, actions/js/1.0/Dockerfile, actions/js/1.0/dice.yml, actions/js/1.0/internal/pkg/build/execute.go, actions/js/1.0/internal/pkg/conf/conf.go, actions/release/1.0/dice.yml, actions/release/1.0/internal/conf/conf.go, actions/release/1.0/internal/pkg/docker.go, actions/release/1.0/internal/pkg/migration.go
support custom buildkitd address
=> feat: support custom buildkitd address

actions/js-pack/1.0/.gitignore, actions/js-pack/1.0/Dockerfile, actions/js-pack/1.0/README.md, actions/js-pack/1.0/dice.yml, actions/js-pack/1.0/index.js, actions/js-pack/1.0/nvm_install.sh, actions/js-pack/1.0/package-lock.json, actions/js-pack/1.0/package.json, actions/js-pack/1.0/rollup.config.js, actions/js-pack/1.0/spec.yml
add new js build action for better log and enable debug in container.
=> feat: add js pack action

actions/release/1.0/dice.yml, actions/release/1.0/internal/pkg/docker.go
https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMjg2LDEyOTcsMTI4MCwxMjUwLDEyMjQsMTIxOCwxMTkwXSwiYXNzaWduZWUiOlsiMTAwMTA3MyJdfQ%3D%3D&id=306001&iterationID=1280&pId=0&type=BUG
=> feat: Optimize release docker push error log.

actions/buildpack-aliyun/1.0/README.md, actions/buildpack/1.0/README.md
=> chore: polish buildpack doc

actions/android/1.0/Dockerfile, actions/android/1.0/dice.yml, actions/android/1.0/internal/conf/conf.go, actions/android/1.0/internal/pkg/build/build.go, actions/android/1.0/spec.yml
android action support multi target
[issue-link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=321455&iterationID=1297&pId=0&type=REQUIREMENT)
=> feat: android action support multi target

dockerfiles/terminus-herd/herd.1.1.11-debian-node.14.17/Dockerfile, dockerfiles/terminus-herd/herd.1.1.18-debian-node.14.19/Dockerfile, dockerfiles/terminus-herd/herd.1.1.18-debian-node.14.19/deploy.sh, dockerfiles/terminus-nodejs/node.14.19.3/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.14.19.3/deploy.sh
Add new docker file for node 14.19 and herd 1.1.18
=> Add new docker file for node 14.19 and herd 1.1.18

dockerfiles/terminus-herd/herd.1.1.18-debian-node.14.19/Dockerfile, dockerfiles/terminus-herd/herd.1.1.18-debian-node.14.19/deploy.sh, dockerfiles/terminus-nodejs/node.14.19.3/Dockerfile.debian.npm.6.14, dockerfiles/terminus-nodejs/node.14.19.3/deploy.sh
=> feat: specify arch of docker image

actions/docker-push/1.0/dice.yml, actions/docker-push/1.0/internal/main.go, actions/docker-push/1.0/spec.yml
=> feat: Add output image in docker-push action.

actions/release/1.0/dice.yml, actions/release/1.0/internal/diceyml/define.go, actions/release/1.0/internal/pkg/diceyml.go, actions/release/1.0/internal/pkg/execute.go, actions/release/1.0/internal/pkg/migration.go
=> fix: add checking image

actions/mobile-publish/1.0/Dockerfile, actions/mobile-publish/1.0/dice.yml, actions/mobile-publish/1.0/internal/push/api.go, actions/mobile-publish/1.0/internal/push/run.go
mobile publish judge resource type
=> fix: mobile publish judge resource type

actions/android/1.0/base_image/Dockerfile
=> Update minimum node version for android action to v14

actions/app-create/1.0/spec.yml
=> fix: app-create action fetch app failed

actions/android/1.0/Dockerfile, actions/android/1.0/base_image/build.sh, actions/android/1.0/dice.yml
=> fix: upgrade android node version

actions/buildpack/1.0/dice.yml, actions/java-build/1.0/dice.yml, actions/java/1.0/dice.yml
=> feature: new version build action

actions/custom-script/1.0/Dockerfile, actions/custom-script/1.0/README.md, actions/custom-script/1.0/dice.yml, actions/custom-script/2.0/Dockerfile, actions/custom-script/2.0/dice.yml
upgrade custom script golang version to 1.17
=> feat: upgrade custom script golang version to 1.17

actions/sonar/1.0/Dockerfile, actions/sonar/1.0/dice.yml, actions/sonar/1.0/internal/analysis.go, actions/sonar/1.0/spec.yml
=> fix: sonar action 1.0 typo

.gitignore, actions/sonar/1.0/dice.yml, actions/sonar/1.0/internal/analysis.go, actions/sonar/1.0/internal/conf.go, actions/sonar/1.0/spec.yml
sonar 1.0 action support java libraries param
=> feat: sonar 1.0 action support java libraries param

actions/buildpack-aliyun/1.0/bp/java/pack/springboot-asia/Dockerfile, actions/buildpack-aliyun/1.0/bp/java/pack/springboot/Dockerfile, actions/buildpack-aliyun/1.0/dice.yml, actions/buildpack-aliyun/1.0/internal/run/build/buildartifact/metafile.go, actions/buildpack/1.0/bp/java/pack/springboot-asia/Dockerfile, actions/buildpack/1.0/bp/java/pack/springboot/Dockerfile, actions/buildpack/1.0/dice.yml, actions/java-build/1.0/dice.yml, actions/java/1.0/comp/openjdk/Dockerfile, actions/java/1.0/dice.yml, dockerfiles/terminus-openjdk/openjdk.v1.8.0.181/Dockerfile, dockerfiles/terminus-openjdk/openjdk.v1.8.0.272/Dockerfile, dockerfiles/terminus-openjdk/openjdk.v11.0.9.11/Dockerfile
Remove arthas, deal with security issues
=> feature: remove arthas

actions/sonar/1.0/dice.yml, actions/sonar/1.0/internal/analysis.go
=> fix: show all quality gate detail

dockerfiles/terminus-herd/herd.1.1.19-debian-node.16.16/Dockerfile, dockerfiles/terminus-herd/herd.1.1.19-debian-node.16.16/deploy.sh, dockerfiles/terminus-nodejs/node.16.16/Dockerfile.debian.npm.8.11, dockerfiles/terminus-nodejs/node.16.16/deploy.sh
Add node 16.16 LTS related docker files
=> Add node 16.16 LTS related docker files

actions/custom-script/1.0/dice.yml
update custom-script 1.0 image
=> fix: update custom-script 1.0 image

actions/js/1.0/dice.yml
=> recover js action image
